# *******************************************************************
# This message was defined by Seokwon Kim (seokwonkim111@gmail.com)
# 2018.03.21 Initial version
# *******************************************************************

float32 x_m
float32 y_m
float32 z_m

float32 FR_x_m
float32 FR_y_m

float32 FL_x_m
float32 FL_y_m

float32 RR_x_m
float32 RR_y_m

float32 RL_x_m
float32 RL_y_m

float32 vx_mps
float32 vy_mps
float32 vz_mps

float32 ax_mps2
float32 ay_mps2
float32 az_mps2

float32 yaw_deg
float32 pitch_deg
float32 roll_deg

float32 x_cov
float32 y_cov
float32 z_cov

float32 vx_cov
float32 vy_cov
float32 vz_cov
float32 x_vx_cov
float32 y_vy_cov

float32 ax_cov
float32 ay_cov
float32 az_cov

float32 yaw_cov
float32 pitch_cov
float32 roll_cov
