# *******************************************************************
# This message was defined by Seokwon Kim (seokwonkim111@gmail.com)
# 2018.03.21 Initial version
# *******************************************************************

float32 s_m
float32 n_m
float32 u_m

float32 FR_s_m
float32 FR_n_m

float32 FL_s_m
float32 FL_n_m

float32 RR_s_m
float32 RR_n_m

float32 RL_s_m
float32 RL_n_m

float32 vs_mps
float32 vn_mps
float32 vu_mps

float32 as_mps2
float32 an_mps2
float32 au_mps2

float32 yaw_deg
float32 pitch_deg
float32 roll_deg
